// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARziTtro81erz5X8NTcGpIfAjc4I3UdKY',
    appId: '1:146792137585:android:d93cbc3d63efe9628f2cd0',
    messagingSenderId: '146792137585',
    projectId: 'cash-n-carry-50c46',
    storageBucket: 'cash-n-carry-50c46.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRS0naZlkBmlVL4d1NQ2kjbJjDM9K-3P0',
    appId: '1:146792137585:ios:0be62f8753b0f8d88f2cd0',
    messagingSenderId: '146792137585',
    projectId: 'cash-n-carry-50c46',
    storageBucket: 'cash-n-carry-50c46.appspot.com',
    iosClientId: '146792137585-vsnvhvvl3k4kbdblgd2amrut7id78blp.apps.googleusercontent.com',
    iosBundleId: 'com.techsensei.cashncary',
  );
}
